### ISSUE TITLE
Uncaught TypeError: The "data" argument must be one of type string, Buffer, TypedArray, or DataVi...

### ISSUE THREAD

**Issue by Anjana-ops** [msansoni/atom-path-copy#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [path-copy](https://github.com/msansoni/atom-path-copy) package 0.14.0

### Stack Trace

Uncaught TypeError: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type object

```
At internal/crypto/hash.js:65

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type object
    at Hash.update (internal/crypto/hash.js:65:11)
    at Clipboard.md5 (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:775553)
    at Clipboard.write (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:775626)
    at Object.writeToClipboard (/packages/path-copy/lib/path-copy.coffee:165:24)
    at Object.copyProjectPath (/packages/path-copy/lib/path-copy.coffee:211:10)
    at /packages/path-copy/lib/path-copy.coffee:85:42)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:349963)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:11:348438)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:765678)
    at EventEmitter.t (~/AppData/Local/atom/app-1.52.0/resources/app/static/<embedded>:1:773684)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (~/AppData/Local/atom/app-1.52.0/resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
     -5:38.2.0 application:open-file (ul.list-inline.tab-bar.inset-panel)
     -5:31.3.0 editor:newline-below (input.hidden-input)
  2x -5:30 core:backspace (input.hidden-input)
     -5:27.3.0 symbols-view:toggle-file-symbols (input.hidden-input)
     -3:00.3.0 core:confirm (input.hidden-input)
     -2:29.1.0 core:save (input.hidden-input)
     -2:28.7.0 core:select-all (input.hidden-input)
     -2:27 core:confirm (input.hidden-input)
     -1:29.9.0 path-copy:fullpath (div.title)
     -0:54 path-copy:fullname (div.title)
     -0:47.2.0 path-copy:shortname (div.title)
     -0:29.7.0 path-copy:extension (div.title)
     -0:23.9.0 path-copy:shortname (div.title)
     -0:08.0 path-copy:projectpath (div.title)
```

### Non-Core Packages

```
path-copy 0.14.0 
```

**Comment by msansoni** [comment]
Fixed with #8
