### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of null

### ISSUE THREAD

**Issue by jpromocion** [msansoni/atom-path-copy#8]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    X* Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    X* Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

exception when using copy

### Steps to Reproduce

1. open atom
2. in tab file, right botton mouse
3. option: Path Copy -> Copy Full Name (or any other Copy)
4. uncaught exception

**Expected behavior:**

Copy filename to clipboard windows

**Actual behavior:**

uncaught exception

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Windows 10 Pro
**Thrown From**: [path-copy](https://github.com/msansoni/atom-path-copy) package 0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of null

```
At C:\Users\jgalvez\.atom\packages\path-copy\lib\path-copy.coffee:184

TypeError: Cannot read property 'item' of null
    at Object.getTabPath (/packages/path-copy/lib/path-copy.coffee:184:20)
    at Object.parseTabPath (/packages/path-copy/lib/path-copy.coffee:194:20)
    at Object.copyFullName (/packages/path-copy/lib/path-copy.coffee:202:28)
    at /packages/path-copy/lib/path-copy.coffee:83:39)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:352694)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:351169)
    at AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:1:833477)
    at EventEmitter.t (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:1:841531)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -0:15 command-palette:toggle (input.hidden-input)
     -0:12.2.0 core:move-down (input.hidden-input)
     -0:11.9.0 core:confirm (input.hidden-input)
     -0:11.9.0 structure-view:show (input.hidden-input)
     -0:08.8.0 path-copy:fullname (div.title)
```

### Non-Core Packages

```
atom-beautify 0.33.4
atom-ide-ui 0.13.0
atom-maven 1.3.2
auto-encoding 0.7.2
autocomplete-jsp 1.2.1
autocomplete-oracle 1.4.4
autocomplete-sql 0.5.0
autocomplete-xml 0.11.0
build 0.70.0
build-oracle 1.6.1
busy-signal 2.0.1
color-picker 2.3.0
css-color-name 0.4.0
docblockr 0.14.2
file-watcher 2.0.0
git-plus 8.7.1
highlight-selected 0.17.0
java-generator-plus 2.6.0
language-oracle 1.9.0
minimap 4.40.0
multi-cursor 3.0.0
obsidian-j-syntax 1.3.0
open-files 0.8.4
open-recent 5.0.0
path-copy 0.14.0
pigments 0.40.6
platformio-ide-terminal 2.10.1
project-manager 3.3.8
split-diff 1.6.1
structure-view 0.2.1
Sublime-Style-Column-Selection 1.7.5
teletype 0.13.4
todo-show 2.3.2
tortoise-svn 0.5.1
xml-formatter 0.13.0
```

### Additional Information

**Comment by softwarecreations** [comment]
It used to work for me before, but is broken for me as well now.
Full path copy, it crashes.
`Uncaught TypeError: Cannot read property 'item' of null`

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Debian GNU/Linux
**Thrown From**: [path-copy](https://github.com/msansoni/atom-path-copy) package 0.14.0


### Stack Trace

Uncaught TypeError: Cannot read property 'item' of null

```
At .atom/packages/path-copy/lib/path-copy.coffee:184

TypeError: Cannot read property 'item' of null
    at Object.getTabPath (/packages/path-copy/lib/path-copy.coffee:184:20)
    at Object.copyFullPath (/packages/path-copy/lib/path-copy.coffee:217:28)
    at /packages/path-copy/lib/path-copy.coffee:81:39)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:352694)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/static/<embedded>:11:351169)
    at AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/static/<embedded>:1:786982)
    at EventEmitter.t (/usr/share/atom/resources/app/static/<embedded>:1:795036)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

**Comment by softwarecreations** [comment]
I hacked it to make copying the full path work. It will copy the full path of the active tab. (not the tab that you right clicked)

edit .atom/packages/path-copy/lib/path-copy.coffee
Lines 176 to 186
```
    getTabContextClicked: ->
        return document.querySelector('ul.tab-bar li.texteditor.tab.active div.title') # I wrote this
        # return document.querySelector('.right-clicked') # commented this out

    getTabPath: (current)->
      if current == true
        return atom.workspace.getActivePaneItem().getURI()
      else
        tab = @getTabContextClicked()
        return tab.dataset.path; # I wrote this
        # return tab.item.getURI()# commented this out
```

The full path is the only thing I care about, so it's the only thing I "fixed"
Note that if/when this package gets updated then these changes that you make will be lost.
Restart atom after making these changes.

**Comment by softwarecreations** [comment]
I hacked it again
Got rid of all the useless options

Much less fiddly now, just one click, not click and carefully move mouse sideways then click again.

Lines 124 - 143
```
        atom.contextMenu.add
            '.tab': [{
                #label: 'Path Copy'
                label: 'Copy full path'  # I changed this label
                command: 'path-copy:fullpath', visible: contextMenuOptions.isCopyFullPath  # I added this line
                # submenu: [  # I commented out this array
                #     {label: 'Copy Full Path', command: 'path-copy:fullpath', visible: contextMenuOptions.isCopyFullPath}
                #     {label: 'Copy Full Name', command: 'path-copy:fullname', visible: contextMenuOptions.isCopyFullName}
                #     {label: 'Copy Short Name', command: 'path-copy:shortname', visible: contextMenuOptions.isCopyShortName}
                #     {label: 'Copy Extension', command: 'path-copy:extension', visible: contextMenuOptions.isCopyExtension}
                #     {type: 'separator'}
                #     {label: 'Copy Folder Path', command: 'path-copy:folderpath', visible: contextMenuOptions.isCopyFolderPath}
                #     {label: 'Copy Project Path', command: 'path-copy:projectpath', visible: contextMenuOptions.isCopyProjectPath}
                #     {label: 'Copy Relative Path', command: 'path-copy:relativepath', visible: contextMenuOptions.isCopyRelativePath}
                #     {type: 'separator'}
                #     {label: 'Add Options in Settings', command: '', visible: !anyVisible, enabled: false}
                # ]
            },
            {type: 'separator'}
            ]
```

**Comment by wsabol** [comment]
building off what [softwarecreations](https://github.com/softwarecreations) did to suppress errors from tabs like Settings and commit diffs that don't have paths - 

```
getTabPath: (current)->
      if current == true
        return atom.workspace.getActivePaneItem().getURI()
      else
        tab = @getTabContextClicked()
        # return tab.item.getURI()# commented this out
        if tab != null # I wrote this
            return tab.dataset.path; # softwarecreations wrote this
            
```

**Comment by msansoni** [comment]
@softwarecreations and @wsabol thanks for your proposals, using some endpoints that have been exposed in Atom since this package's last version, I've re-written the path retreival to solve the issues above. Commit: [
67e4128](https://github.com/msansoni/atom-path-copy/commit/67e4128f1f15a54f15810642a093cae1f0548486)
